version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: container_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretpw
      MYSQL_DATABASE: ProjetOPA
      MYSQL_USER: user
      MYSQL_PASSWORD: secretpw
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local

# Penser à installer mysql-client dans le container