name: Action
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Continuous Integration
        run: |
          cd docker_loader
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/cryptobot_loader:latest
          cd ../docker_api
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/cryptobot_api:latest
          cd ../docker_test_api
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/cryptobot_api_test:latest
          cd ../docker_training
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/model_training:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/cryptobot_loader:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cryptobot_api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cryptobot_api_test:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/model_training:latest
      - name: Continuous Deployment 1
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: docker_compose/docker-compose.yml
          target: /home/${{ secrets.USERNAME }}/${{ secrets.DOCKER_USERNAME }}
      - name: Continuous Deployment 2
        uses: appleboy/ssh-action@v1.0.3
        env: 
          MARIADB_PW: ${{ secrets.MARIADB_PW }}
          MONGODB_PW: ${{ secrets.MONGODB_PW }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: MARIADB_PW,MONGODB_PW
          script: |
            cd projetopa/docker_compose
            docker-compose down
            docker pull ${{ secrets.DOCKER_USERNAME }}/cryptobot_loader:latest
            docker rmi $(docker images --filter "dangling=true" -q)
            docker pull ${{ secrets.DOCKER_USERNAME }}/cryptobot_api:latest
            docker rmi $(docker images --filter "dangling=true" -q)            
            docker pull ${{ secrets.DOCKER_USERNAME }}/model_training:latest
            docker rmi $(docker images --filter "dangling=true" -q)            
            docker-compose up -d database mariadb
            sleep 10
            docker-compose up -d data_loader
            sleep 5
            docker-compose up -d cryptobot_api
            sleep 5
            docker-compose up -d model_training