name: Action
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Continuous Integration
        env: 
          MARIADB_PW: ${{ secrets.MARIADB_PW }}
          MONGODB_PW: ${{ secrets.MONGODB_PW }}
        run: |
          cd docker_loader
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/cryptobot_loader:latest
          cd ../docker_api
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/cryptobot_api:latest
          cd ../docker_test_api
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/cryptobot_api_test:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/cryptobot_loader:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cryptobot_api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cryptobot_api_test:latest
      - name: Continuous Deployment 1
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 34.240.175.91
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: docker_compose/docker-compose.yml
          target: /home/${{ secrets.USERNAME }}/projetopa
      - name: Continuous Deployment 2
        uses: appleboy/ssh-action@v1.0.3
        env: 
          MARIADB_PW: ${{ secrets.MARIADB_PW }}
          MONGODB_PW: ${{ secrets.MONGODB_PW }}
        with:
          host: 34.240.175.91
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd projetopa
            docker-compose down
            docker pull ${{ secrets.DOCKER_USERNAME }}/cryptobot_loader:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/cryptobot_api:latest            
            docker-compose up -d database mariadb
            docker-compose up -d data_loader
            docker-compose up -d cryptobot_api
