name: Action
on:
  pull_request:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Continuous Integration
        env: 
          MARIADB_PW: ${{ secrets.MARIADB_PW }}
          MONGODB_PW: ${{ secrets.MONGODB_PW }}
        run: |
          cd docker_loader
          docker build . -t cryptobot_loader:latest
          cd ../docker_api
          docker build . -t cryptobot_api:latest
          cd ../docker_test_api
          docker build . -t cryptobot_api_test:latest
          cd ../docker_compose
          docker-compose up -d database mariadb
          docker-compose up -d data_loader
          docker-compose up -d cryptobot_api
          docker-compose up -d cryptobot_api_test
